server:
  port: 8300
spring:
  application:
    name: qs-blog
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qs_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    com.ninng: debug
